from tkinter import NS, EW


widgets = {
    "frame": {
        "widget": {"bg": 'lightCyan2', "width": 40, "relief": "raised"},
        "grid": {"padx": 4},
        "widgets": [{"name": "root", "parent": "mw", "widget": {}, "grid": {}},
                    {"name": "left", "parent": "root", "widget": {}, "grid": {"row": 0, "column": 0, "sticky": NS}},
                    {"name": "center", "parent": "root", "widget": { "width": 120}, "grid": {"row": 0, "column": 1}},
                    {"name": "right", "parent": "root", "widget": {}, "grid": {"row": 0, "column": 2, "sticky": NS}},
                    {"name": "title", "parent": "left", "widget": {}, "grid": {"sticky": EW, "pady": 2}},
                    {"name": "current", "parent": "left", "widget": {}, "grid": {"sticky": EW, "pady": 8}},
                    {"name": "command", "parent": "left", "widget": {}, "grid": {}},
                    {"name": "selection", "parent": "center", "widget": {}, "grid": {"sticky": EW}},
                    {"name": "query", "parent": "center", "widget": {}, "grid": {"sticky": (EW, NS), "pady": 2}},
                    {"name": "input", "parent": "center", "widget": {}, "grid": {"sticky": EW, "pady": 2}},
                    {"name": "control", "parent": "center", "widget": {}, "grid": {"pady": 2}},
                    {"name": "message", "parent": "right", "widget": {}, "grid": {"sticky": EW, "pady": 2}},
                    {"name": "plate", "parent": "right", "widget": {}, "grid": {"sticky": EW, "pady": 8}},
        ]
    },
    "listbox": {
        "widget": {"height": 13, "width": 25},
        "grid": {"row": 1, "rowspan": 12, "sticky": NS},
        "widgets": [{"name": "target_edition", "parent": "selection", "widget": {"height": 4}, "grid": {"column": 0, "rowspan": 3}},
                    {"name": "group", "parent": "selection", "widget": {"height": 8}, "grid": {"row": 5, "column": 0, "rowspan": 14}},
                    {"name": "source", "parent": "selection", "widget": {}, "grid": {"column": 2}},
                    {"name": "category", "parent": "selection", "widget": {}, "grid": {"column": 4}},
                    {"name": "table", "parent": "selection", "widget": {}, "grid": {"column": 6}},
        ],
    },"listbox!": {
        "widget": {"height": 18, "width": 15},
        "grid": {"row": 1, "rowspan": 14, "sticky": NS},
        "widgets": [{"name": "query_name", "parent": "query", "widget": {}, "grid": {"column": 0}},
                    {"name": "query", "parent": "query", "widget": {"width": 105},
                     "grid": {"column": 2, "sticky": (EW, NS)}, "other": {"scrollbar_h": True}},
        ],
    },"listbox!!": {
        "widget": {"height": 6, "width": 25},
        "grid": {"rowspan": 6, "sticky": NS},
        "widgets": [{"name": "message_box", "parent": "message", "widget": {}, "grid": {"row": 1, "column": 0},
                     "other": {"scrollbar": False}},
        ],
    },
    "Label": {
        "widget": {"text": '', "bg": 'lightCyan2'},
        "grid": {"sticky": 'EW'},
        "widgets": [{"name": "target", "parent": "title", "widget": {}, "grid": {}},
                    {"name": "edition", "parent": "title", "widget": {}, "grid": {}},
                    {"name": "url", "parent": "title", "widget": {}, "grid": {}},
                    {"name": "group", "parent": "current", "widget": {}, "grid": {}},
                    {"name": "source", "parent": "current", "widget": {}, "grid": {}},
                    {"name": "category", "parent": "current", "widget": {}, "grid": {}},
                    {"name": "item", "parent": "current", "widget": {}, "grid": {}},
                    {"name": "url", "parent": "current", "widget": {}, "grid": {}},
                    {"name": "target_edition", "parent": "selection", "widget": {}, "grid": {"row": 0, "column": 0}},
                    {"name": "group", "parent": "selection", "widget": {}, "grid": {"row": 4, "column": 0}},
                    {"name": "source", "parent": "selection", "widget": {}, "grid": {"row": 0, "column": 2}},
                    {"name": "category", "parent": "selection", "widget": {}, "grid": {"row": 0, "column": 4}},
                    {"name": "table", "parent": "selection", "widget": {}, "grid": {"row": 0, "column": 6}},
                    {"name": "name", "parent": "query", "widget": {"text": "Item Name"}, "grid": {"row": 0, "column": 0}},
                    {"name": "data", "parent": "query", "widget": {"text": "Item Data"}, "grid": {"row": 0, "column": 2}},
                    {"name": "kitchen_cli", "parent": "input", "widget": {"text": "Kitchen CLI"}, "grid": {"row": 0, "column": 0}},
                    {"name": "sqlite_cli", "parent": "input", "widget": {"text": "SQLite CLI"}, "grid": {"row": 1, "column": 0}},
                    {"name": "", "parent": "plate", "widget": {"text": "Plate:"}, "grid": {}},
                    {"name": "name", "parent": "plate", "widget": {}, "grid": {}},
                    {"name": "url", "parent": "plate", "widget": {}, "grid": {}},
                    {"name": "category", "parent": "plate", "widget": {}, "grid": {}},
                    {"name": "status", "parent": "plate", "widget": {}, "grid": {}},
        ]
    },
    "Entry": {
        "widget": {},
        "grid": {"column": 1, "sticky": EW},
        "widgets": [{"name": "kitchen_cli", "parent": "input", "widget": {"width": 60}, "grid": {"row": 0}},
                    {"name": "sql_cli", "parent": "input", "widget": {"width": 105}, "grid": {"row": 1}},
        ]
    },
    "Button": {
        "widget": {"bg": "grey", "width": 20, "default": "disabled"},
        "grid": {"padx": 2, "pady": 2},
        "widgets": [{"name": "clear_message_box", "parent": "message", "widget": {}, "grid": {"row": 0, "column": 0}},
                    {"name": "export_model_to_app", "parent": "plate", "widget": {}, "grid": {}},
                    {"name": "extract_sources", "parent": "command", "widget": {}, "grid": {}},
                    {"name": "sort_sources", "parent": "command", "widget": {}, "grid": {}},
                    {"name": "cook_url", "parent": "command", "widget": {}, "grid": {}},
                    {"name": "parse_item", "parent": "command", "widget": {}, "grid": {}},
                    {"name": "fit_item_to_model", "parent": "command", "widget": {}, "grid": {}},
                    {"name": "cook_category", "parent": "command", "widget": {}, "grid": {}},
                    {"name": "parse_category", "parent": "command", "widget": {}, "grid": {}},
                    {"name": "fit_category_to_model", "parent": "command", "widget": {}, "grid": {}},
                    {"name": "cook_selection", "parent": "command", "widget": {}, "grid": {}},
                    {"name": "parse_selection", "parent": "command", "widget": {}, "grid": {}},
                    {"name": "fit_selection_to_models", "parent": "command", "widget": {}, "grid": {}},
                    {"name": "update_ica", "parent": "control", "widget": {}, "grid": {"row": 0, "column": 0}},
                    {"name": "update_provider", "parent": "control", "widget": {}, "grid": {"row": 0, "column": 1}},
                    {"name": "update_parser", "parent": "control", "widget": {}, "grid": {"row": 0, "column": 2}},
                    {"name": "update_normalizer", "parent": "control", "widget": {}, "grid": {"row": 0, "column": 3}},
                    {"name": "update_modeler", "parent": "control", "widget": {}, "grid": {"row": 0, "column": 4}},

        ]
    },
}